package GUI;

import distributedassignment.Coordinator;
import distributedassignment.Message;
import distributedassignment.Node;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CoordinatorControl extends javax.swing.JFrame {

    Coordinator n;

    public CoordinatorControl() {
        initComponents();
    }

    public CoordinatorControl(Coordinator n) {
        initComponents();
        this.n = n;
        this.n.setCn(this);
        this.userCount.setText("Current users: " + this.n.getRingNetwork().getRing().size());

        //Initialize controller Node GUI as usual
        NodeGUI ngd = new NodeGUI(n);
        ngd.setVisible(true);
        this.refreshCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeMessage = new javax.swing.JLabel();
        userCount = new javax.swing.JLabel();
        joinRequests = new javax.swing.JLabel();
        joinList = new javax.swing.JComboBox<>();
        acceptButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        joinRequests1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notificationsBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 255));

        welcomeMessage.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        welcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setText("Control Panel");

        userCount.setForeground(new java.awt.Color(255, 255, 255));
        userCount.setText("Current users: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(welcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(userCount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(welcomeMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userCount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        joinRequests.setText("Join Requests:");

        joinList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinListMouseClicked(evt);
            }
        });
        joinList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinListActionPerformed(evt);
            }
        });

        acceptButton.setBackground(new java.awt.Color(0, 102, 102));
        acceptButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(204, 0, 0));
        rejectButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        joinRequests1.setText("Notifications:");

        notificationsBox.setEditable(false);
        notificationsBox.setColumns(20);
        notificationsBox.setRows(5);
        jScrollPane1.setViewportView(notificationsBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(joinRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(joinList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(acceptButton)
                        .addGap(67, 67, 67)
                        .addComponent(rejectButton))
                    .addComponent(joinRequests1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joinRequests1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinRequests))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(rejectButton))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_joinListMouseClicked

    private void joinListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinListActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_joinListActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        try {
            Integer joinSelected = Integer.valueOf((String) this.joinList.getSelectedItem());
            Node selected = null;
            for (Node n : this.n.getJoining()) {
                if (n.getHostID() == joinSelected) {
                    selected = n;
                    String announcement = "Accepted " + "[ " + selected.getName() + " ] " + "\n";
                    this.notificationsBox.append(announcement);
                    this.n.addToNetwork(selected);
                    this.joinList.removeItem(joinSelected);
                }
            }
            NodeGUI nd = new NodeGUI(selected, this.n);
            nd.setVisible(true);

            this.refreshLists();
            this.refreshCount();
        } catch (Exception e) {
            System.out.println("Can neither Accept nor Reject empty fields");
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        try {

            Integer joinSelected = Integer.valueOf((String) this.joinList.getSelectedItem());
            Node selected = null;
            for (Node n : this.n.getJoining()) {
                if (n.getHostID() == joinSelected) {
                    selected = n;

                    String announcement = "Rejected " + "[ " + selected.getName() + " ] " + "\n";
                    this.notificationsBox.append(announcement);
                    this.n.leaveJoin(selected);
                    this.joinList.removeItem(joinSelected);
                }
            }

            this.refreshLists();
            this.refreshCount();
        } catch (Exception e) {
            System.out.println("Can neither Accept nor Reject empty fields");
        }
    }//GEN-LAST:event_rejectButtonActionPerformed

    public void refreshLists() {
        this.joinList.removeAllItems();
        for (Node n : this.n.getJoining()) {
            this.joinList.addItem((Integer.toString(n.getHostID())));
        }
        if (this.joinList.getSelectedItem() != null) {
            this.joinList.setSelectedIndex(0);
        }
    }

    public void refreshCount() {
        this.userCount.setText("Current users:" + this.n.getRingNetwork().getRing().size());
    }

    public void nodeLeft(Node n) {
        String announcement = "[ " + n.getName() + " ] " + "left the network \n";
        this.notificationsBox.append(announcement);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoordinatorControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoordinatorControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoordinatorControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoordinatorControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoordinatorControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> joinList;
    private javax.swing.JLabel joinRequests;
    private javax.swing.JLabel joinRequests1;
    private javax.swing.JTextArea notificationsBox;
    private javax.swing.JButton rejectButton;
    private javax.swing.JLabel userCount;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
